# Generated by Django 2.2.5 on 2020-06-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=100)),
                ('class_teacher_of', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=10)),
                ('subject_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Teaches',
            },
        ),
    ]
