# Generated by Django 2.2.5 on 2020-06-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_image',
            field=models.ImageField(default='user.jpeg', upload_to='teacher'),
        ),
    ]
