# Generated by Django 2.2.5 on 2020-06-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teacher', '0003_auto_20200607_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='class_teacher_of',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
