# Generated by Django 2.2.5 on 2020-06-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teacher', '0004_auto_20200609_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAndSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10)),
                ('subject_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ClassAndSubject',
            },
        ),
    ]
