# Generated by Django 2.2.5 on 2020-06-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Subjects',
            },
        ),
    ]
