# Generated by Django 2.2.5 on 2020-06-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('student', '0003_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.IntegerField()),
                ('subject_code', models.CharField(max_length=10)),
                ('mid1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mid2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subject_teacher', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Marks',
            },
        ),
    ]
