# Generated by Django 2.2.5 on 2020-06-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('student', '0004_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
