# Generated by Django 2.2.5 on 2020-06-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('student', '0005_auto_20200601_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='percentage',
        ),
        migrations.AddField(
            model_name='student',
            name='percentage_of_final',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='percentage_of_mid1',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='percentage_of_mid2',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
