# Generated by Django 2.2.5 on 2020-06-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('student', '0006_auto_20200605_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='percentage_of_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='percentage_of_mid1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='percentage_of_mid2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
