# Generated by Django 2.2.5 on 2020-06-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('student', '0007_auto_20200605_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_image',
            field=models.ImageField(default='user.jpeg', upload_to='student_<django.db.models.fields.CharField>'),
        ),
    ]
