# Generated by Django 2.2.5 on 2020-06-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('student', '0008_student_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(default='user.jpeg', height_field=100,
                                    upload_to='student_<django.db.models.fields.CharField>', width_field=100),
        ),
    ]
