# Generated by Django 2.2.5 on 2020-06-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('student', '0010_auto_20200607_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(default='user.jpeg', upload_to='student_image'),
        ),
    ]
