# Generated by Django 2.2.5 on 2020-06-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('student', '0011_auto_20200607_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='marks',
            name='mid1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='marks',
            name='mid2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
