# Generated by Django 2.2.5 on 2020-06-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('student', '0012_auto_20200613_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='subject_teacher',
            field=models.CharField(default='Not Assigned', max_length=20),
        ),
    ]
